# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_delete_locationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Address', max_length=45)),
            ],
        ),
    ]
