# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_pointofinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='position',
            new_name='location',
        ),
    ]
