# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20160323_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_PV', models.FloatField()),
                ('array_Efficiency', models.FloatField()),
                ('inverter_Efficiency', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('tilt', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('albedo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WindSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_Wind', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
