# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20160324_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
