# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20160325_0426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastDataModel',
        ),
        migrations.DeleteModel(
            name='SolarSettingsModel',
        ),
        migrations.DeleteModel(
            name='WindSettingsModel',
        ),
    ]
