# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20160325_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ix', models.DateTimeField()),
                ('solarForecast', models.FloatField()),
                ('windForecast', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cloudCover', models.FloatField()),
            ],
        ),
    ]
