# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20160326_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdatamodel',
            old_name='cloudCover',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='datetime_ix',
        ),
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='solarForecast',
        ),
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='windForecast',
        ),
    ]
