# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20160326_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastDataModel',
        ),
    ]
