# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_delete_forecastdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ix', picklefield.fields.PickledObjectField(editable=False)),
                ('solarForecast', picklefield.fields.PickledObjectField(editable=False)),
                ('windForecast', picklefield.fields.PickledObjectField(editable=False)),
                ('temperature', picklefield.fields.PickledObjectField(editable=False)),
                ('humidity', picklefield.fields.PickledObjectField(editable=False)),
                ('cloudCover', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
