# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20160326_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdatamodel',
            old_name='datetime_ix',
            new_name='time',
        ),
    ]
