# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20160326_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdatamodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='forecastdatamodel',
            name='cloudCover',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastdatamodel',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastdatamodel',
            name='solarForecast',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastdatamodel',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastdatamodel',
            name='windForecast',
            field=models.FloatField(),
        ),
    ]
