# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_auto_20160327_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdatamodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 14, 51, 33, 329406, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
